version: '3.8'

services:
  web:
    image: tfs-web:latest
    restart: always
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=https://tfs.ma
      - POCKETBASE_URL=http://pocketbase:8090
      - POCKETBASE_ADMIN_EMAIL=zakiossama28@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=GloXoss123.
      - NEXT_PUBLIC_SITE_URL=https://tfs.ma
      - NEXT_PUBLIC_SITE_NAME=TFS Equipment Rentals
      - RESEND_API_KEY=re_QvDHbKzY_NyPwDXss25gr818B1CmuiUui
      - EMAIL_FROM=TFS <noreply@zouskym.com>
      - ADMIN_EMAIL=zakiossama28@gmail.com
      - AI_PROVIDER=openrouter
      - OPENROUTER_API_KEY=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
      - AI_MODEL=z-ai/glm-4.5-air:free
      - NEXT_PUBLIC_ENABLE_DIGITAL_SIGNATURE=true
      - ENABLE_CLIENT_PORTAL=false
      - PORT=3000
    networks:
      - tfs-network

  pocketbase:
    image: tfs-pb:latest
    restart: always
    volumes:
      - ./pb_data:/pb/pb_data
    networks:
      - tfs-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
      - pocketbase
    networks:
      tfs-network:
        aliases:
          - tfs.ma

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - tfs-network

networks:
  tfs-network:
    driver: bridge
